### PR TITLE
derive Clone for UseEventSourceError

### PR DESCRIPTION
**Pull request by littlebenlittle**
Start fix for #109

### CODE REVIEW

**Comment by maccesch** [comment]
Looking good! Thanks for your work!

**Comment by maccesch** [comment]
Closing this as it's not strictly necessary and there hasn't been any activity in a while

**Comment by mdecimus** [comment]
Any chances this PR will be merged?

I am having the same issue not being able to call `get` on the error signal.

**Comment by maccesch** [comment]
This is due to the fact, that we can't really know if the error is clone or not. It is a bit unfortunate but you can use `.with()` instead.

**Comment by mdecimus** [comment]
> This is due to the fact, that we can't really know if the error is clone or not. It is a bit unfortunate but you can use .with() instead.

That's fine, I'll use `with` instead.

Thanks for the quick reply!

**Pull request closed without merging**
