### PR TITLE
Improve use_storage and removing storage flag

### PR DESCRIPTION
**Pull request by feral-dot-io**
The use_storage API is great but there are a few issues with it:

* It is locked behind the storage feature.
* It requires usage of serde, a large dependency.
* Versioning is done with `merge_defaults` and is pure string replacement.
* It fails if the storage is disabled.
* There is possibly a race condition between an internal and global storage event.

This is a merge request to improve on these points.

The API now requires a codec to be specified. This codec specifies how a value should be encoded and decoded to the browser API. I've introduced the following codecs:
* StringCodec: a simple parser relies on FromStr and ToString. Used by default and works with primitive values. Doesn't require a feature flag.
* JsonCodec: parses the value as JSON. Usage of this codec is the same as before and uses the "serde" feature.
* ProstCodec: parses the value as a protocol buffer message. This is a codec that handles versioning and uses the "prost" feature.

By using a codec, the API can be used without enabling any features:
```
let (count, set_count, remove) = use_local_storage::<i32, StringCodec>("my-count");
```

JSON can be used just as easily. It also expands to any struct that implements Serialize, Deserialize as before:
```
let (count, set_count, remove) = use_session_storage::<i32, JsonCodec>("my-count-kept-in-js");
```

I've had to make changes to the API to support this. I've tried to keep the same functionality as before. General high-level changes to the API:
* The `use_storage_with_options` is the base fn that takes a StorageType, key and options. This forces a choice between local / session / custom whose semantics are different rather than relying on a default.
* The `use_local_storage` and `use_session_storage` (and those having the _with_options suffix) call into `use_storage_with_options`.
* Instead of passing a default, `UseStorageOptions` provides a default signal that uses `T::default` if not provided.
* `write_defaults` was removed as it wasn't obvious what should happen if the storage was deleted. If the storage item is removed, the value reverts back to the default signal.
* `merge_defaults` was removed as it's a choice made by the codec.

Other points of interest:
* The storage feature flag has been removed.
* These changes touch `use_color_mode` which can now attempts data persistence without the storage feature.
* There's a fallback to just using signals if browser storage is disabled. It acts a lot like a lesser session storage.
* In the original design, values are passed and read from the event. I wasn't sure how these global events interacted from multiple tabs as well as internal events. So I switched the read signal to be a memo that calls storage.get_item when notified by an external event. This should avoid any data races from competing events.

Things I think that need your careful consideration:
* Added `thiserror` dependency. It's a small, macro dependency but a dependency nevertheless.
* Missing guidance on how to replace `merge_defaults`. This could just be an example on how to implement Codec and manipulating the JSON string as before. Or another JsonValueCodec that gives you access to the Serde::Value to make better default decisions than string replace. Your input here would be useful. It might also be obvious as the Codec trait is rather simple and might not need anything.
* The default value of `UseColorModeOptions::storage_enabled` flips based on whether the storage flag was enabled. Since this flag has gone away and is now effectively always enabled, it will flip to true for users not previously using storage. I think this is reasonable but might be a surprise.
* I tried using the default_builder macros but this resulted in an error related to the codecs. So I kept it as the manual builder pattern.
* The `UseStorageOptions::default_value` is a `MaybeRwSignal` but only the read portion is used. I kept it as rw because it impacted the colour mode API and I wanted to avoid the ripple effect of changing too many APIs.

Please let me know what you think and give any feedback as necessary. I'm more than happy to make changes and tweaks as needed. I am away this week so my time is limited but I will try to do what I can.

### CODE REVIEW

**Comment by maccesch** [comment]
Thanks, this is awesome! Thanks for all this great work. I think it'll improve `use_storage` a lot.

I like the idea of `Codecs` a lot!

Feedback to your raised points:

- `thiserror` is totally fine. In another branch I'm adding this dependency myself.
- I think versioning is indeed a consideration here. Maybe the function doc should include a section for that that mentions that Prost has it already and how to do it in JSON?
- I agree, having storage enabled for color mode is totally a sensible default.
- The default builder macro supports `#[builder(skip)]` attributes on fields. That field can then be implemented manually while all others don't need to. Would you mind making that change?
- If you look at the previous code you'll see that the returned `data` and `set_data` signals are actually coming from the `default`'s `MaybeRwSignal`'s. The idea is - as is done in `use_color_mode` - that you can have an existing `RwSignal` working as before but it gets a storage inserted. We should really keep this functionality.

There's another thing: The way we generate the book from doc comments is not very intelligent. It requires at the moment that the first entity with doc comments is the actualy function (`use_storage` in this case) and everything else comes after.

Thanks again!

**Comment by feral-dot-io** [comment]
I'm glad you like it!

I don't mind making the changes. I'll review the following:
- Document an overview of versioning options.
- Document how to version JSON as currently documented.
- Document how best to version with JSON.
- Switch to the builder macro with `#[builder(skip)]`
- Fix the mdbook docgen. 
- Finally, I'll look at data / set_data returning the MaybeRwSignal from defaults. The reason for the current approach was trying to avoid race conditions from competing events. I think it should be possible but it'll require careful review.

I'll do all of this next week when I'm back.

**Comment by feral-dot-io** [comment]
I've completed what you've asked for. Three things came up.

The first was with deriving data / set_data from the MaybeRwSignal. I was able to do this without issue but the default signal is less of a signal but more of a way to pass an "initial value" whenever the key isn't set. This initial value can't be changed for the life of the hook. I think this is a bit of a surprise because if I'm passing a signal, I'd assume the derived value (in this case the storage hook) would also change when it depends on it. This is what the initial PR was doing. I resolved this by renaming "default_value" to "initial_value" and mentioning it in the docs.

The second thing was related to the builder. It seems like the were compilation errors were on the struct itself using two generics. So I didn't make any changes to it.

Finally, I had some issues with building the mdbook. The scripts couldn't find post_build.sh for `use_service_worker` but did build when I deleted this part of the book. I renamed use_storage to use_storage_with_options but it wasn't parsing and pulling in the docs like the rest of the book. It also still mentions the "feature = storage" line. I'm not familiar with Python so I'm not easily able amend the Python scripts to fix this.

**Comment by maccesch** [comment]
Thanks!

1. To being able to build the book you have move all structs in the file use_storage.rs below the functions `use_storage` and `use_storage_with_options`. Actually, in order to being able to review the changes meaningfully I'd appreciate it if you didn't change the order of the data structures. 😄 
2. Please document the fields on `UseStorageOptions`.

**Comment by feral-dot-io** [comment]
1a) I was able to build the book. The problem was a post build script. Fix in #47.
1b) Once it was building I was able to understand what was happening in `extract_doc_comment.py`. Wow! I've done a small reorganisation to get the mdbook docs working.
1c) I've reverted to the original order (needed for mdbook). This PR started life as a complete rewrite of use_storage.
2) Done.
3) Done.

**Comment by maccesch** [comment]
Thank you so very much!!

I brought back `use_storage` (without options) as I don't think we should break things if we don't need to.

Also I brought back the `## Demo` section in the docs because in the book this is where the live demo is copied in.

Just FYI in case I didn't scare you off and you'll add more PRs in the future 😀

**Pull request merged**
