### PR TITLE
Add `*_local` variants for filtered signals.

### PR DESCRIPTION
**Pull request by bicarlsen**
Implemented and tested for `debounce`.

### CODE REVIEW

**Comment by maccesch** [comment]
Thanks! This is a very useful addtion. It duplicates quite a lot of code though. Can we instead adjust the `signal_filttered!` macro to also cover the `_local` variants?

**Comment by bicarlsen** [comment]
I tried using generics over [`Storage`](https://docs.rs/leptos/latest/leptos/reactive/owner/trait.Storage.html) but [`Into<Signal>` in not implemented for generic storage `ReadSignal`s, only `SyncStorage` and `LocalStorage`](https://docs.rs/leptos/latest/leptos/prelude/struct.Signal.html#impl-From%3CReadSignal%3CT,+LocalStorage%3E%3E-for-Signal%3CT,+LocalStorage%3E). This creates an issue [when converting the filtered `ReadSignal` into a `Signal`](https://github.com/Synphonyte/leptos-use/blob/14576235356b6861588365216a892d405cdee22e/src/utils/signal_filtered.rs#L60).

e.g.
```rust
pub fn [<signal_ $filter_name d_with_options>]<S, T, St>(
    value: S,
    ms: impl Into<Signal<f64>> + 'static,
    options: [<$filter_name:camel Options>],
) -> Signal<T, St>
where
    S: Into<Signal<T, St>>,
    T: Clone + Send + Sync + 'static,
    St: Storage<SignalTypes<T, St>> + Storage<T>,
{
    // ...

    let (filtered, set_filtered) = RwSignal::new_with_storage(value.get_untracked()).split();

    // ...

   filtered.into() // can not convert to `Signal` over generic `Storage`
}
```

**Comment by maccesch** [comment]
I think we don't necessarily need to make it generic but can do some macro-fu to implement it.

**Comment by bicarlsen** [comment]
Ah, got ya. I'm not so experienced with macros but can certainly give it a go.

**Comment by maccesch** [comment]
Nice work, thanks!

**Comment by bicarlsen** [comment]
A note for future work:

I don't think [`signal_filtered_macro_impl`](https://github.com/Synphonyte/leptos-use/blob/4f265477ce6b690e3a8633c1d3df80bbfbdca5c4/src/utils/signal_filtered.rs#L43) is implemented in the nicest way, particularly with regard to how the [additional trait bounds are provided](https://github.com/Synphonyte/leptos-use/blob/4f265477ce6b690e3a8633c1d3df80bbfbdca5c4/src/utils/signal_filtered.rs#L51).

A nicer implementation would allow the additional trait bounds to be passed in as `TraitA + TraitB`, but `+` is a special character for macros, and I couldn't figure out how to escape it.

**Comment by maccesch** [comment]
Noted 👍

**Pull request merged**
