### PR TITLE
Upgraded to 0.6 :)

### PR DESCRIPTION
**Pull request by rakshith-ravi**

### CODE REVIEW

**Comment by rakshith-ravi** [comment]
Oh FML! Actix hasn't upgraded to http 1 yet. Great

**Comment by rakshith-ravi** [comment]
I HATE the hacky workaround I'm doing, but whatever. Let me know if this fine

**Comment by rakshith-ravi** [comment]
@maccesch that testing problem we discussed about is popping up here. And actix isn't willing to upgrade to http1 until 0.5 (https://github.com/actix/actix-web/pull/3208#issuecomment-1837204631) so we're gonna have to do a workaround till then

**Comment by maccesch** [comment]
Thanks! I didn't even know that you can specify dependencies like that. Looks good to me. Once Actix updates we can simplify but until then I think this is a good solution.

**Comment by rakshith-ravi** [comment]
Wait, so how are we gonna make a new release with the tests failing?

**Comment by paul-hansen** [comment]
The tests are failing because if you enable both features you're defining the headers variable twice. If you think about it, when you call `cargo test --all-features` which version of the use_cookie function are you expecting it to use? 

There are two ways I've seen things like this handled:

### Option A: Prevent enabling both features

```rust
#[cfg(all(feature = "foo", feature = "bar"))]
compile_error!("Only one feature \"foo\" or \"bar\" may be enabled for this crate.");

#[cfg(all(feature = "actix", not(feature="axum")))]
const COOKIE: http0_2::HeaderName = http0_2::header::COOKIE;
#[cfg(all(feature = "axum", not(feature="actix"))]
const COOKIE: http1::HeaderName = http1::header::COOKIE;

#[cfg(any(feature = "axum", feature="actix")] // <-- important so people using custom integrations can still use leptos-use
pub fn use_cookie(cookie_name: &str) -> Option<Cookie<'static>> {
```
Update the github action to call `cargo test --axum` and `cargo test --actix` separately.

**Cons**
- No single command to run all tests.
- Not really idiomatic as Rust features should be additive and not mutually exclusive according to the [docs](https://doc.rust-lang.org/cargo/reference/features.html?#feature-unification):
  > A consequence of this is that features should be additive. That is, enabling a feature should not disable functionality, and it should usually be safe to enable any combination of features.
   
### Option B (my preference): Separate modules for platform specific implementations

You can have two different files/modules for the two integrations that have the same/similar function signatures in them. Users would then import from the appropriate module for their integration like so:
```rust
// Axum
use leptos_use::axum::use_context;

// Actix
use leptos_use::actix::use_context:
```
**Cons**
- Some code duplication (can mitigate somewhat with private functions that are shared between them for common parts of the implementation. use_cookie is small enough already though).

**Comment by rakshith-ravi** [comment]
Thanks for that write up!

Yes, this has already been discussed with @maccesch and I in a private DM. These were the approaches we had in mind, the question was more of "what's the plan to make a release with a failing build" rather than "how do we solve this". We have a few solutions in mind that would mitigate this in the future, so this is just for a temporary workaround we need to do till actix 5 releases

**Pull request merged**
